apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-release-redis-master
            port:
              number: 6379
